insert into Oils (oilId, codeName, fullName) values (1, 'Enalapril Maleate', 'Eachelle Speakman');
insert into Oils (oilId, codeName, fullName) values (2, 'CURAD Isopropyl Alcohol', 'Hertha Verbeke');
insert into Oils (oilId, codeName, fullName) values (3, 'Cyzone', 'Isador Wombwell');
insert into Oils (oilId, codeName, fullName) values (4, 'Awaken by Quality Choice Illuminating Daily Moisturizer Broad Spectrum SPF 15 Sunscreen', 'Rycca Freeborne');
insert into Oils (oilId, codeName, fullName) values (5, 'LOSARTAN POTASSIUM', 'Collie McClinton');
insert into Oils (oilId, codeName, fullName) values (6, 'Metoprolol succinate', 'Alameda Garz');
insert into Oils (oilId, codeName, fullName) values (7, 'CITALOPRAM HYDROBROMIDE', 'Kalinda Cuddihy');
insert into Oils (oilId, codeName, fullName) values (8, 'Ambien CR', 'Terrence Harbage');
insert into Oils (oilId, codeName, fullName) values (9, 'Pseudoephedrine Hydrochloride', 'Bartholomeus Tsar');
insert into Oils (oilId, codeName, fullName) values (10, 'Treatment Set TS333375', 'Nicholle Sabey');
insert into Oils (oilId, codeName, fullName) values (11, 'Alpha E-3', 'Rennie Marriott');
insert into Oils (oilId, codeName, fullName) values (12, 'levalbuterol inhalation', 'Ginelle MacGille');
insert into Oils (oilId, codeName, fullName) values (13, 'Dermoneen', 'Tatum Menhci');
insert into Oils (oilId, codeName, fullName) values (14, 'Systemic Drainage', 'Doreen Draysay');
insert into Oils (oilId, codeName, fullName) values (15, 'Gyno Complex', 'Cammy Grisard');
insert into Oils (oilId, codeName, fullName) values (16, 'ANTI-WRINKLE AND FIRMING BROAD SPECTRUM SPF18 SUNSCREEN', 'Loni McDougle');
insert into Oils (oilId, codeName, fullName) values (17, 'Day Cream SPF 30', 'Ingar Kerwin');
insert into Oils (oilId, codeName, fullName) values (18, 'Eight Hour Cream Lip Protectant Sheer Tint SPF 15 Melon', 'Garald Clampton');
insert into Oils (oilId, codeName, fullName) values (19, 'AcipHex', 'Viviyan Sheard');
insert into Oils (oilId, codeName, fullName) values (20, 'Beefwood/Australian Pine', 'Prissie Hunton');
