version: "3.9"
services:
    ev-oil-db:
        container_name: ev-oil-db
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "VerySecurePassword321"
            ACCEPT_EULA: "Y"
        ports:
            - "8000:1433"
