version: "3.8"
services:
  ev-oil:
    container_name: ev-oil
    image: ev-oil:latest
    restart: unless-stopped
    build:
      
      dockerfile: EvOil.WebApi/Dockerfile
    ports:
      - "9000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "development"
      CONNECTIONSTRINGS__LOCALDATABASE: "Server=ev-oil-db,1433;Database=EvOilDb;User Id=SA;Password=VerySecurePassword321;"
